### ISSUE TITLE
AccessViolationException

### ISSUE THREAD

**Issue by pengweiqhca** [BepInEx/HarmonyX#39]
```
System.AccessViolationException
   at HarmonyLib.Internal.RuntimeFixes.StackTraceFixes.GetMethodFix(System.Diagnostics.StackFrame)
   at System.Diagnostics.StackTrace.ToString(TraceFormat)
   at System.Exception.GetStackTrace(Boolean)
   at System.Exception.ToString(Boolean, Boolean)
   at System.String.Concat(System.Object, System.Object)
   at System.Web.HttpRuntime.ReleaseResourcesAndUnloadAppDomain(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by pengweiqhca** [comment]
In asp.net (not core), when asp.net restart, iisexpress/w3wp crash. The stack trace from windows events.
